<a href="https://colab.research.google.com/github/vineethreddy56/npl/blob/main/nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [145]:
import pandas as pd
messages = pd.read_csv('spam.csv', encoding='latin-1')
messages = messages[['v1', 'v2']].rename(columns={'v1': 'label', 'v2': 'message'})
#messages=messages.drop(['Unnamed: 2','Unnamed: 3','Unnamed: 4'],axis=1)
#messages=messages[['v1','v2']]
messages
#messages.head()


label                                            message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [146]:
messages['message'].iloc[500]

'Fighting with the world is easy, u either win or lose bt fightng with some1 who is close to u is dificult if u lose - u lose if u win - u still lose.'

In [147]:
import re
import nltk
#nltk.download('stopwords')
from nltk.corpus import stopwords
#from nltk.stem.porter import PorterStemmmer
stemmer=PorterStemmer()
print(stemmer.stem('happy'))
print(lemmatizer.lemmatize('happy'))


happi
happy


In [148]:
#stemming

In [149]:
corpus=[]
for i in range(len(messages)):
  review=re.sub('[^a-zA-Z0-9]',' ',messages['message'][i])
  review=review.lower()
  review=review.split()
  review=[stemmer.stem(word) for word in review if word not in stopwords.words('english')]
  review=' '.join(review)
  corpus.append(review)

In [150]:
corpus[0]

'go jurong point crazi avail bugi n great world la e buffet cine got amor wat'

In [151]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500)
X=cv.fit_transform(corpus).toarray()

In [152]:
#y value indicates ham=false and spam=true

In [153]:
y=pd.get_dummies(messages['label'])
y=y.iloc[:,1].values
y

array([False, False,  True, ..., False, False, False])

In [154]:
from sklearn.model_selection import  train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,y,test_size=0.2,random_state=0)


In [155]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train,Y_train)
y_pred=spam_detect_model.predict(X_test)

In [156]:
y_pred

array([False, False, False, ..., False, False, False])

In [157]:
from sklearn.metrics import accuracy_score,classification_report
accuracy_score(Y_test,y_pred)

0.9865470852017937

In [158]:
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

       False       0.99      0.99      0.99       949
        True       0.96      0.95      0.95       166

    accuracy                           0.99      1115
   macro avg       0.98      0.97      0.97      1115
weighted avg       0.99      0.99      0.99      1115



In [159]:
#lemmitization

In [160]:
corp=[]
for i in range(len(messages)):
  review=re.sub('[^a-zA-Z0-9]',' ',messages['message'][i])
  review=review.lower()
  review=review.split()
  review=[lemmatizer.lemmatize(word) for word in review if word not in stopwords.words('english')]
  review=' '.join(review)
  corp.append(review)

In [161]:
corp[0]

'go jurong point crazy available bugis n great world la e buffet cine got amore wat'

In [162]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_features=2500,binary=True,ngram_range=(3,3))
x=cv.fit_transform(corp).toarray()


In [163]:
y=pd.get_dummies(messages['label'])
y=y.iloc[:,1].values
y

array([False, False,  True, ..., False, False, False])

In [164]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [165]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model=MultinomialNB().fit(X_train,Y_train)
y_pred=spam_detect_model.predict(X_test)

In [166]:
from sklearn.metrics import accuracy_score,classification_report
accuracy_score(Y_test,y_pred)

0.9372197309417041

In [167]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,y_pred))

              precision    recall  f1-score   support

       False       0.93      1.00      0.96       949
        True       1.00      0.58      0.73       166

    accuracy                           0.94      1115
   macro avg       0.97      0.79      0.85      1115
weighted avg       0.94      0.94      0.93      1115



In [ ]:
#Tfidf

In [168]:
from sklearn.feature_extraction.text import TfidfVectorizer
tc=TfidfVectorizer()
x=cv.fit_transform(corpus).toarray()


In [169]:
Y=pd.get_dummies(messages['label'],drop_first=True)
Y=Y.values.ravel()

In [170]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(x,Y,test_size=0.2,random_state=0)

In [171]:
from sklearn.naive_bayes import MultinomialNB
spam_detect_model = MultinomialNB().fit(X_train, Y_train)
predx=spam_detect_model.predict(X_test)
predx

array([False, False, False, ..., False, False, False])

In [172]:
from sklearn.metrics import accuracy_score
print(accuracy_score(Y_test,predx))


0.9399103139013453


In [173]:
from sklearn.metrics import classification_report
print(classification_report(Y_test,predx))

              precision    recall  f1-score   support

       False       0.93      1.00      0.97       949
        True       1.00      0.60      0.75       166

    accuracy                           0.94      1115
   macro avg       0.97      0.80      0.86      1115
weighted avg       0.94      0.94      0.93      1115



In [174]:
!pip install gensim

In [175]:
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

In [176]:
wv['happy'].shape

(300,)

In [177]:
wv.similarity('happy','sad')

0.5354614

In [178]:
from nltk.stem import WordNetLemmatizer
lemmatizer=WordNetLemmatizer()

In [179]:
corp=[]
for i in range(len(messages)):
  review=re.sub('[^a-zA-Z0-9]',' ',messages['message'][i])
  review=review.lower()
  review=review.split()

  review=[lemmatizer.lemmatize(word) for word in review if word not in stopwords.words('english')]
  review=" ".join(review)
  corp.append(review)

In [180]:
corp[0]

'go jurong point crazy available bugis n great world la e buffet cine got amore wat'

In [181]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

In [182]:
words=[]
for sent in corp:
  sent_token=sent_tokenize(sent)
  for sent in sent_token:
    words.append(simple_preprocess(sent))


In [183]:
len(words)

5565

In [184]:
import gensim

In [185]:
#training word2vec model

In [186]:
model=gensim.models.Word2Vec(words,window=5,min_count=2)

In [187]:
model.wv.index_to_key[:10]

['call', 'get', 'ur', 'gt', 'lt', 'go', 'ok', 'free', 'day', 'know']

In [188]:
model.corpus_count

5565

In [189]:
model.epochs

5

In [190]:
model.wv['happy'].shape

(100,)

In [191]:
model.wv.similar_by_word("history")

[('fat', 0.9647606015205383),
 ('pub', 0.9637190103530884),
 ('town', 0.9633861184120178),
 ('notice', 0.9628605246543884),
 ('kinda', 0.9623088240623474),
 ('sch', 0.9621489644050598),
 ('complimentary', 0.9619750380516052),
 ('digital', 0.9617733955383301),
 ('smoke', 0.9614477753639221),
 ('em', 0.9613819718360901)]

In [192]:
#performing avgword2vec

In [193]:
import numpy as np

In [194]:
def avg_Word2Vec(doc):
  return np.mean([model.wv[word] for word in doc if word in model.wv.index_to_key],axis=0)

In [195]:
!pip install tqdm

In [196]:
from tqdm import tqdm

In [197]:
type(model.wv.index_to_key)

list

In [198]:
X=[]
for i in tqdm(range(len(words))):
    X.append(avg_Word2Vec(words[i]))

  0%|          | 0/5565 [00:00<?, ?it/s]/usr/local/lib/python3.11/dist-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.11/dist-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
100%|██████████| 5565/5565 [00:01<00:00, 4350.26it/s]


In [199]:
(X)[0]

array([-0.12126533,  0.22955799,  0.08907857, -0.02082307,  0.04786314,
       -0.34533772,  0.12052935,  0.4418274 , -0.21332484, -0.15942724,
       -0.1265123 , -0.46292648,  0.02540858,  0.07622679,  0.0311617 ,
       -0.20435804, -0.07170134, -0.27343452,  0.07967712, -0.4386517 ,
        0.1375711 ,  0.15696369,  0.03618394, -0.06336145, -0.10671229,
        0.00436302, -0.17173423, -0.19608895, -0.23152821,  0.03660437,
        0.25701323,  0.0565729 ,  0.02330897, -0.15719135, -0.09265715,
        0.23095809, -0.01100504, -0.21352424, -0.07315754, -0.48872742,
       -0.02277274, -0.19531886, -0.07985298,  0.07254285,  0.2258512 ,
       -0.09032703, -0.2119491 , -0.10316842,  0.17510742,  0.20125757,
        0.17224878, -0.23485953, -0.06499482, -0.07829237, -0.15302679,
        0.1007752 ,  0.19464964, -0.02852692, -0.27616268,  0.07806111,
        0.07105397,  0.0588633 , -0.1145753 , -0.07028329, -0.32536492,
        0.20555393,  0.09876642,  0.2348664 , -0.2955468 ,  0.29